# Basic Numpy Calculation

In [1]:
import numpy as np

## 넘파이 배열 생성

In [4]:
num_arr = np.array([1.0, 2.0, 3.0])
num_arr2 = np.array([[1,2,3], [4,5,6]])
print("1차원 배열")
print(num_arr, '\n')
print("2차원 배열")
print(num_arr2)

1차원 배열
[1. 2. 3.] 

2차원 배열
[[1 2 3]
 [4 5 6]]


In [11]:
num_arr2.shape

(2, 3)

In [12]:
num_arr2.dtype

dtype('int64')

## 넘파이 산술 연산

In [5]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [6]:
x+y

array([3., 6., 9.])

In [7]:
x*y

array([ 2.,  8., 18.])

In [8]:
x-2

array([-1.,  0.,  1.])

In [9]:
x*2

array([2., 4., 6.])

## 브로드캐스팅 

In [13]:
A = np.array([[1,2], [3,4]])
B = np.array([[3,0],[0,6]])

In [14]:
A*B

array([[ 3,  0],
       [ 0, 24]])